csv_path: "../raw_data/all_data_info.csv"
img_dir: "../raw_data/train_1"
# img_dir: "../testie"
# model_path: "../model/artnet"
output_patches: "patches/"
output_json: "data_for_shallow/"
# output_json: "test_data_for_shallow/"
cnn_input_size: 325
checkpoint_path: "checkpoint5.pth"
